# Generated by Django 2.0.1 on 2018-01-28 22:40

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Pen Art', ''), ('Pencil Art', ''), ('Painting', '')], max_length=50)),
                ('small_img_url', models.FileField(unique=True, upload_to='gallery/graphics/')),
                ('large_img_url', models.ImageField(unique=True, upload_to='gallery/graphics/')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('company_logo_url', models.ImageField(unique=True, upload_to='clients/')),
            ],
        ),
        migrations.CreateModel(
            name='GraphicsGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Logo', ''), ('Banner', ''), ('Flyer', ''), ('Book Cover', ''), ('Ticket', ''), ('Business Card', ''), ('Frame', ''), ('Invitation Card', ''), ('Poster', '')], max_length=50)),
                ('small_img_url', models.FileField(unique=True, upload_to='gallery/graphics/')),
                ('large_img_url', models.ImageField(unique=True, upload_to='gallery/graphics/')),
            ],
        ),
        migrations.CreateModel(
            name='IllustrationGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Technical', 'Illustrations of parts of a mechanism or an object(vehicle)'), ('Scientific', 'Illustrations of scientific processes, reactions and matter'), ('Medical', 'Illustrations of Medical processes, nature, systems and so on'), ('Book', 'Illustrations found in books to illustrate the chapter of page in question'), ('Children', 'Illustration to enhance learning in children like cartoons, shapes and figures'), ('Comic', ''), ('Publication', ''), ('Advertisment', ''), ('Product', ''), ('Teaching', ''), ('Charts', '')], max_length=50)),
                ('small_img_url', models.FileField(unique=True, upload_to='gallery/illustraton/')),
                ('large_img_url', models.ImageField(unique=True, upload_to='gallery/illustraton/')),
            ],
        ),
        migrations.CreateModel(
            name='MotionGraphicsGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Pen Art', ''), ('Pencil Art', ''), ('Painting', '')], max_length=50)),
                ('small_img_url', models.FileField(unique=True, upload_to='gallery/graphics/')),
                ('large_img_url', models.ImageField(unique=True, upload_to='gallery/graphics/')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image_url', models.ImageField(unique=True, upload_to='services/')),
                ('description', models.TextField()),
                ('fontawesome_icon', models.CharField(max_length=25)),
                ('sub_services', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_fullname', models.CharField(max_length=100)),
                ('customer_post', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=80)),
                ('testimony', models.CharField(max_length=200)),
                ('thumbnail_url', models.ImageField(null=True, upload_to='testimonies/thumbnails/')),
            ],
        ),
        migrations.CreateModel(
            name='WebGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=50)),
                ('site_link', models.URLField(max_length=100)),
                ('mobile_img_url', models.ImageField(unique=True, upload_to='gallery/web/')),
                ('web_img_url', models.ImageField(unique=True, upload_to='gallery/web/')),
            ],
        ),
    ]
