# Generated by Django 2.0.1 on 2018-01-29 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('site_link', models.URLField(max_length=100)),
                ('mobile_img_url', models.ImageField(unique=True, upload_to='gallery/site/web/')),
                ('web_img_url', models.ImageField(unique=True, upload_to='gallery/site/mobile/')),
            ],
        ),
        migrations.DeleteModel(
            name='WebGallery',
        ),
        migrations.RemoveField(
            model_name='testimony',
            name='customer_post',
        ),
        migrations.AlterField(
            model_name='artgallery',
            name='category',
            field=models.CharField(choices=[('Pen Art', 'nothing'), ('Pencil Art', 'nothing'), ('Painting', 'nothing')], max_length=50),
        ),
        migrations.AlterField(
            model_name='artgallery',
            name='small_img_url',
            field=models.ImageField(unique=True, upload_to='gallery/graphics/'),
        ),
        migrations.AlterField(
            model_name='graphicsgallery',
            name='small_img_url',
            field=models.ImageField(unique=True, upload_to='gallery/graphics/'),
        ),
        migrations.AlterField(
            model_name='illustrationgallery',
            name='small_img_url',
            field=models.ImageField(unique=True, upload_to='gallery/illustraton/'),
        ),
        migrations.AlterField(
            model_name='motiongraphicsgallery',
            name='category',
            field=models.CharField(choices=[('Educational', 'nothing'), ('Cartoon', 'nothing'), ('Advertisment', 'nothing')], max_length=50),
        ),
        migrations.AlterField(
            model_name='motiongraphicsgallery',
            name='large_img_url',
            field=models.FileField(unique=True, upload_to='gallery/motiongraphics/'),
        ),
        migrations.AlterField(
            model_name='motiongraphicsgallery',
            name='small_img_url',
            field=models.FileField(unique=True, upload_to='gallery/motiongraphics/'),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='company',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='testimony',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='thumbnail_url',
            field=models.ImageField(null=True, unique=True, upload_to='testimonies/thumbnails/'),
        ),
    ]
