# Generated by Django 2.0.1 on 2018-01-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0003_auto_20180129_0821'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyJovinx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
    ]
