# Generated by Django 2.0.1 on 2018-01-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0007_jovinxinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jovinxinfo',
            name='address1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jovinxinfo',
            name='address2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jovinxinfo',
            name='headquarters_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jovinxinfo',
            name='job_mail_address',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='jovinxinfo',
            name='mobile',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jovinxinfo',
            name='official_mail_address',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='jovinxinfo',
            name='official_phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jovinxinfo',
            name='site_url',
            field=models.URLField(default='http://www.jovinx.com.ng'),
        ),
        migrations.AlterField(
            model_name='jovinxinfo',
            name='support_mail_address',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='jovinxinfo',
            name='whatsapp',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
