# Generated by Django 2.0.1 on 2018-02-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0013_message_servicerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.EmailField(editable=False, max_length=254),
        ),
        migrations.AlterField(
            model_name='message',
            name='first_name',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='last_name',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='messsage',
            field=models.TextField(editable=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='phone',
            field=models.BigIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='email',
            field=models.EmailField(editable=False, max_length=254),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='first_name',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='last_name',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='phone',
            field=models.BigIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='service_requested',
            field=models.CharField(choices=[('Web Development', 'Web Development'), ('Graphics Design', 'Graphics Design'), ('Illustration Design', 'Illustration Design'), ('Life Drawing', 'Life Drawing'), ('Digital Marketing', 'Digital Marketing'), ('SEO Integration', 'SEO Integration'), ('Site Maintenance', 'Site Maintenance'), ('Web Hosting', 'Web Hosting')], editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='specifications',
            field=models.TextField(editable=False),
        ),
    ]
