# Generated by Django 2.0.1 on 2018-03-01 23:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0014_auto_20180209_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='messsage',
        ),
        migrations.AddField(
            model_name='message',
            name='message',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='message',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='service_requested',
            field=models.CharField(choices=[('Web Development', 'Web Development'), ('Graphics Design', 'Graphics Design'), ('Illustration Design', 'Illustration Design'), ('Life Drawing', 'Life Drawing'), ('Digital Marketing', 'Digital Marketing'), ('SEO Integration', 'SEO Integration'), ('Site Maintenance', 'Site Maintenance'), ('Web Hosting', 'Web Hosting'), ('Training', 'Training'), ('Art', 'Art'), ('Software Dev', 'Software Dev')], max_length=200),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='specifications',
            field=models.TextField(blank=True, null=True),
        ),
    ]
