# Generated by Django 2.0.1 on 2018-03-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0016_mailsubscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whyjovinx',
            name='description',
            field=models.TextField(max_length=150),
        ),
    ]
