# Generated by Django 2.0.1 on 2018-03-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0017_auto_20180303_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailSubscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MailSubscribers',
        ),
    ]
