# Generated by Django 2.0.1 on 2018-03-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0018_auto_20180303_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='service_requested',
            field=models.CharField(choices=[('Web Development', 'Web Development'), ('Graphics Design', 'Graphics Design'), ('Illustration Design', 'Illustration Design'), ('Pictorial skills', 'Pictorial skills'), ('Digital Marketing', 'Digital Marketing'), ('SEO Integration', 'SEO Integration'), ('Site Maintenance', 'Site Maintenance'), ('Web Hosting', 'Web Hosting'), ('Training', 'Training'), ('Software Dev', 'Software Dev')], max_length=200),
        ),
    ]
